jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  
  steps:
    # Cache/restore the vcpkg's build artifacts.
  - task: Cache@2
    displayName: 'Cache vcpkgs artifacts'
    inputs:
      key: $(Build.SourcesDirectory)/vcpkg_windows.txt | "$(vcpkgGitRef)" | "$(Agent.OS)"
      path: '$(Build.BinariesDirectory)/vcpkg'
  - task: run-vcpkg@0
    displayName: 'Run vcpkg'
    inputs:
      vcpkgArguments: $(Build.SourcesDirectory)/vcpkg_windows.txt
      vcpkgGitURL: https://github.com/microsoft/vcpkg.git
