variables:
  vcpkgGitRef: 1be75a28bfce2084bb0b59ec92a6853f13d7be66

jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'

  steps:
    # Cache/restore the vcpkg's build artifacts.
  - task: Cache@2
    displayName: 'Cache vcpkgs artifacts'
    inputs:
      key: $(Build.SourcesDirectory)/vcpkg_windows.txt | "$(vcpkgGitRef)" | "$(Agent.OS)"
      path: '$(Build.BinariesDirectory)/vcpkg'
  - task: run-vcpkg@0
    displayName: 'Run vcpkg'
    inputs:
      vcpkgArguments: @$(Build.SourcesDirectory)/vcpkg_windows.txt
      vcpkgGitCommitId: $(vcpkgGitRef)
      vcpkgGitURL: https://github.com/microsoft/vcpkg.git
